export enum ErrorCode {
  SUCCESS = 'SUCCESS',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  CONFLICT = 'CONFLICT',
  RATE_LIMITED = 'RATE_LIMITED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_INSUFFICIENT_FUNDS = 'PAYMENT_INSUFFICIENT_FUNDS',
  PAYMENT_CARD_DECLINED = 'PAYMENT_CARD_DECLINED',
  PAYMENT_EXPIRED = 'PAYMENT_EXPIRED',
  PAYMENT_INVALID_AMOUNT = 'PAYMENT_INVALID_AMOUNT',
  SUBMISSION_NOT_FOUND = 'SUBMISSION_NOT_FOUND',
  SUBMISSION_ALREADY_REVIEWED = 'SUBMISSION_ALREADY_REVIEWED',
  SUBMISSION_NOT_REVIEWABLE = 'SUBMISSION_NOT_REVIEWABLE',
  SUBMISSION_INVALID_STATUS = 'SUBMISSION_INVALID_STATUS',
  COURSE_NOT_FOUND = 'COURSE_NOT_FOUND',
  COURSE_ALREADY_ENROLLED = 'COURSE_ALREADY_ENROLLED',
  COURSE_NOT_ENROLLED = 'COURSE_NOT_ENROLLED',
  CHALLENGE_NOT_FOUND = 'CHALLENGE_NOT_FOUND',
  CHALLENGE_ALREADY_COMPLETED = 'CHALLENGE_ALREADY_COMPLETED',
  CHALLENGE_EXPIRED = 'CHALLENGE_EXPIRED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_SUSPENDED = 'USER_SUSPENDED',
  BADGE_ALREADY_EARNED = 'BADGE_ALREADY_EARNED',
  BADGE_REQUIREMENTS_NOT_MET = 'BADGE_REQUIREMENTS_NOT_MET',
  LEADERBOARD_NOT_AVAILABLE = 'LEADERBOARD_NOT_AVAILABLE',
  REWARD_NOT_FOUND = 'REWARD_NOT_FOUND',
  REWARD_ALREADY_CLAIMED = 'REWARD_ALREADY_CLAIMED',
  REWARD_EXPIRED = 'REWARD_EXPIRED',
  API_KEY_INVALID = 'API_KEY_INVALID',
  API_KEY_EXPIRED = 'API_KEY_EXPIRED',
  API_KEY_REVOKED = 'API_KEY_REVOKED',
  API_KEY_RATE_LIMITED = 'API_KEY_RATE_LIMITED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  INVALID_INPUT = 'INVALID_INPUT',
  MISSING_PARAMETER = 'MISSING_PARAMETER',
  INVALID_PARAMETER = 'INVALID_PARAMETER',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
  INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  HTTP_EXCEPTION = 'HTTP_EXCEPTION',
  HINT_NOT_FOUND = 'HINT_NOT_FOUND',
  HINT_TIER_EXCEEDED = 'HINT_TIER_EXCEEDED',
  HINT_CHALLENGE_INACCESSIBLE = 'HINT_CHALLENGE_INACCESSIBLE',
  HINT_COOLDOWN_ACTIVE = 'HINT_COOLDOWN_ACTIVE',
  HINT_MAX_VIEWS_EXCEEDED = 'HINT_MAX_VIEWS_EXCEEDED',
}

export const ERROR_CODE_MESSAGES: Record<ErrorCode, string> = {
  [ErrorCode.SUCCESS]: 'Success',
  [ErrorCode.VALIDATION_ERROR]: 'The request body failed validation',
  [ErrorCode.NOT_FOUND]: 'The requested resource was not found',
  [ErrorCode.UNAUTHORIZED]: 'Authentication is required',
  [ErrorCode.FORBIDDEN]: 'You do not have permission to access this resource',
  [ErrorCode.CONFLICT]: 'The request conflicts with the current state',
  [ErrorCode.RATE_LIMITED]: 'Too many requests, please try again later',
  [ErrorCode.PAYMENT_FAILED]: 'Payment processing failed',
  [ErrorCode.PAYMENT_INSUFFICIENT_FUNDS]: 'Insufficient funds for this transaction',
  [ErrorCode.PAYMENT_CARD_DECLINED]: 'The payment card was declined',
  [ErrorCode.PAYMENT_EXPIRED]: 'The payment session has expired',
  [ErrorCode.PAYMENT_INVALID_AMOUNT]: 'The payment amount is invalid',
  [ErrorCode.SUBMISSION_NOT_FOUND]: 'The submission was not found',
  [ErrorCode.SUBMISSION_ALREADY_REVIEWED]: 'This submission has already been reviewed',
  [ErrorCode.SUBMISSION_NOT_REVIEWABLE]: 'This submission cannot be reviewed in its current state',
  [ErrorCode.SUBMISSION_INVALID_STATUS]: 'Invalid submission status transition',
  [ErrorCode.COURSE_NOT_FOUND]: 'The course was not found',
  [ErrorCode.COURSE_ALREADY_ENROLLED]: 'You are already enrolled in this course',
  [ErrorCode.COURSE_NOT_ENROLLED]: 'You are not enrolled in this course',
  [ErrorCode.CHALLENGE_NOT_FOUND]: 'The challenge was not found',
  [ErrorCode.CHALLENGE_ALREADY_COMPLETED]: 'You have already completed this challenge',
  [ErrorCode.CHALLENGE_EXPIRED]: 'This challenge has expired',
  [ErrorCode.USER_NOT_FOUND]: 'The user was not found',
  [ErrorCode.USER_ALREADY_EXISTS]: 'A user with this identifier already exists',
  [ErrorCode.USER_SUSPENDED]: 'This user account has been suspended',
  [ErrorCode.BADGE_ALREADY_EARNED]: 'You have already earned this badge',
  [ErrorCode.BADGE_REQUIREMENTS_NOT_MET]: 'Badge requirements have not been met',
  [ErrorCode.LEADERBOARD_NOT_AVAILABLE]: 'Leaderboard data is not available',
  [ErrorCode.REWARD_NOT_FOUND]: 'The reward was not found',
  [ErrorCode.REWARD_ALREADY_CLAIMED]: 'This reward has already been claimed',
  [ErrorCode.REWARD_EXPIRED]: 'This reward has expired',
  [ErrorCode.API_KEY_INVALID]: 'The API key is invalid',
  [ErrorCode.API_KEY_EXPIRED]: 'The API key has expired',
  [ErrorCode.API_KEY_REVOKED]: 'The API key has been revoked',
  [ErrorCode.API_KEY_RATE_LIMITED]: 'API key rate limit exceeded',
  [ErrorCode.INTERNAL_ERROR]: 'An unexpected internal error occurred',
  [ErrorCode.SERVICE_UNAVAILABLE]: 'The service is temporarily unavailable',
  [ErrorCode.INVALID_INPUT]: 'The input provided is invalid',
  [ErrorCode.MISSING_PARAMETER]: 'A required parameter is missing',
  [ErrorCode.INVALID_PARAMETER]: 'A parameter has an invalid value',
  [ErrorCode.RESOURCE_CONFLICT]: 'The resource conflicts with another operation',
  [ErrorCode.INSUFFICIENT_PERMISSIONS]: 'Insufficient permissions for this operation',
  [ErrorCode.SESSION_EXPIRED]: 'Your session has expired',
  [ErrorCode.ACCOUNT_LOCKED]: 'This account has been locked',
  [ErrorCode.TOO_MANY_REQUESTS]: 'Too many requests, please try again later',
  [ErrorCode.HTTP_EXCEPTION]: 'An HTTP error occurred',
  [ErrorCode.HINT_NOT_FOUND]: 'No hints available for this challenge',
  [ErrorCode.HINT_TIER_EXCEEDED]: 'You have not unlocked this hint tier yet',
  [ErrorCode.HINT_CHALLENGE_INACCESSIBLE]: 'You do not have access to this challenge',
  [ErrorCode.HINT_COOLDOWN_ACTIVE]: 'Please wait before requesting another hint',
  [ErrorCode.HINT_MAX_VIEWS_EXCEEDED]: 'You have reached the maximum views for this hint',
}
